config/routes.rb
Rails.application.routes.draw do
  root "customers#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/customers/missing_email', to: 'customers#missing_email'
  get '/customers/alphabetized', to: 'customers#alphabetized'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :customers
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one_attached :image

  validates :full_name, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email_address", "full_name", "id", "id_value", "notes", "phone_number", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["image_attachment", "image_blob"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where(email_address: "")
  end

private
  def customer_params
    params.require(:customer).permit(:full_name, :phone_number, :email_address, :notes, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customers.html.erb
 <div class="border border-gray-300 border-solid ml-3 p-5 w-48">
  <h3><%= customer.full_name %></h3>
  <%= image_tag customer.image if customer.image.attached? %>
  <p><%= customer.phone_number %></p>
  <p><%= customer.email_address %></p>
  <p><%= customer.notes %></p>
</div>

app/views/customers/alphabetized.html.erb
<div>
    <ul class="flex list-none">
        <li><%= link_to "All", customers_path %></li>
        <li class="ml-5"><%= link_to "Missing Email", customers_missing_email_path %></li>
    </ul>
</div>

<h1>Customers A-Z</h1>

<div class="flex">
    <% @customers.each do |customer| %>
    <%= render partial: 'customers', locals: {customer: customer} %>
    <% end %>
</div>

app/views/customers/index.html.erb
<h1>All Customers</h1>


<% @customers.each do |customer| %>
<%= render partial: 'customers', locals: { customer: customer } %>
<% end %>

app/views/customers/missing_email.html.erb
<div>
    <ul class="flex list-none">
        <li><%= link_to "All", customers_path %></li>
        <li class="ml-5"><%= link_to "Alphabetcal", customers_alphabetized_path %></li>
    </ul>
</div>
<h1>Customers Without Email</h1>

<div class="flex">
    <% @customers.each do |customer| %>
    <%= render partial: 'customers', locals: {customer: customer} %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>U6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="mx-auto mt-28 flex justify-center ">
      <div>
        <%= yield %>
      </div>
    </main>
  </body>
</html>